### ISSUE TITLE
Where to put response error message

### ISSUE THREAD

**Issue by togimoto** [112-1-Database-Management-Final-Project/ntu-book#12]
In our API document, error messages are put in the "error" property:
<img width="423" alt="image" src="https://github.com/112-1-Database-Management-Final-Project/ntu-book/assets/123284600/a8907c8a-6c8e-48fe-9365-3a2274cc1e36">

But in #11, the error messages are put in the "message" field.

Which one should it be?

**Comment by yenting-biao** [comment]
i think message (?
also, you can modify the API docs

**Comment by togimoto** [comment]
I suggest putting it in the error field, which seems to be the industry convention.

**Comment by yenting-biao** [comment]
I have change my code from `message` to `error`. Should I add a new PR?
