### ISSUE TITLE
SQL table name does not match schema diagram

### ISSUE THREAD

**Issue by quevenliu** [112-1-Database-Management-Final-Project/ntu-book#14]
SQL Table name:
Seller, Buyer

Schema Table:
SellerID, BuyerID

Since the code has already been developed, edit schema table instead of editing SQL table.

**Comment by togimoto** [comment]
Can we rename the attributes in PostgreSQL instead? SellerID and BuyerID is self-documenting.

**Comment by imbensonchiu** [comment]
See #21
