### ISSUE TITLE
Letter casing of student ID

### ISSUE THREAD

**Issue by togimoto** [112-1-Database-Management-Final-Project/ntu-book#16]
In our database, student ID is stored in lowercase. In @quevenliu's auth code, student ID is stored in uppercase.

Which casing should we use? We should maintain consistency with casing to avoid unexpected query errors. Although student IDs are case-insensitive (e.g., z10000000 == Z10000000), NTU always displays capitalized student IDs, so I suggest using uppercase at all times.

**Comment by imbensonchiu** [comment]
By the standard of NTU CINC （台大計中）, I'll prefer the case-insensitive policy.
