### ISSUE TITLE
Missing timestamp attribute in rating relation

### ISSUE THREAD

**Issue by togimoto** [112-1-Database-Management-Final-Project/ntu-book#22]
It feels like the relation `rating` is missing a `timestamp` attribute. Should we add it?

**Comment by quevenliu** [comment]
投加上去一票

**Comment by yenting-biao** [comment]
![image](https://github.com/112-1-Database-Management-Final-Project/ntu-book/assets/91837449/1c5b21d1-3136-4ebd-9476-5bedf94dd27f)
不是有ㄇ

**Comment by togimoto** [comment]
Sorry, I meant the relation `rating`.

**Comment by imbensonchiu** [comment]
@quevenliu  記得改 schema 
@togimoto  @yenting-biao  改 ER Diagram

**Comment by yenting-biao** [comment]
fixed 我要把新的 ER Diagram 放哪裡
