### ISSUE TITLE
gitignore yarn.lock

### ISSUE THREAD

**Issue by quevenliu** [112-1-Database-Management-Final-Project/ntu-book#23]
yarn.lock is a automatically generated file after running yarn install. It might change according to each person's environment and might cause conflict. 

Maybe we can just keep the package.json?

If there is any mistake in my understanding please correct me.

**Comment by togimoto** [comment]
Don't gitignore it.
https://stackoverflow.com/questions/39990017/should-i-commit-the-yarn-lock-file-and-what-is-it-for
