### ISSUE TITLE
Public and private user details

### ISSUE THREAD

**Issue by togimoto** [112-1-Database-Management-Final-Project/ntu-book#27]
Are there any user attributes that a user can see but other users are not allowed to see? i.e., are there any attributes that a user has and that he/she must log in to see (cannot be viewed from public profile page)? This will affect whether or not we need two API endpoints for retrieving user info.

**Comment by yenting-biao** [comment]
看 student id 跟 fname, lname 有沒有要公開吧

**Comment by quevenliu** [comment]
Yesterday I discussed the format of private API with @ZaiKuku, the API format can be found here

https://www.notion.so/bensonchiu/Get-User-Private-Profile-39bc36c5f13e42499b9dd97d40deee10
