### ISSUE TITLE
Book Search did not return results

### ISSUE THREAD

**Issue by ZaiKuku** [112-1-Database-Management-Final-Project/ntu-book#29]
Book Search 不會回傳資料，我用 /api/book?BookName=python抓不到資料，沒有Error

**Comment by yenting-biao** [comment]
![image](https://github.com/112-1-Database-Management-Final-Project/ntu-book/assets/91837449/31535b9a-648f-43b8-a7a4-6c1c2a1d8e38)
我這邊看是有東西的？
