### ISSUE TITLE
Post Purchase Request failed

### ISSUE THREAD

**Issue by ZaiKuku** [112-1-Database-Management-Final-Project/ntu-book#37]
@togimoto
![image](https://github.com/112-1-Database-Management-Final-Project/ntu-book/assets/107979268/0b4618ac-0d6c-4dca-8219-3ff661a56105)

end point not found

**Comment by togimoto** [comment]
我本機測試是沒問題。是不是 auth 的問題？
<img width="1124" alt="addrequesttest" src="https://github.com/112-1-Database-Management-Final-Project/ntu-book/assets/123284600/816b70d8-cff9-41fc-a65a-1751a60d526a">

**Comment by ZaiKuku** [comment]
已解決，我忘記fetch之後重開server...
