### ISSUE TITLE
Backend folder naming

### ISSUE THREAD

**Issue by yenting-biao** [112-1-Database-Management-Final-Project/ntu-book#46]
Should we rename our backend folder from `src/backend` to `backend`? The `src` folder seems useless.

**Comment by togimoto** [comment]
On the contrary, I think `Frontend/` should be placed under `src/`. Additionally, it should be renamed to `frontend/` since it is the only out-of-place capitalized identifier in the repository.

**Comment by yenting-biao** [comment]
> On the contrary, I think `Frontend/` should be placed under `src/`. Additionally, it should be renamed to `frontend/` since it is the only out-of-place capitalized identifier in the repository.

But there will be two src in the frontend path, eg. `src/frontend/src/...`, which is weird. In Next.js, there are other files in the same level with `src` directory.
You can check the directory structure of the reference code of Web Programming, `112-1-unit2-simple-chat-room`, the Next.js server and the Express.js server is in two different folders, `web` and `server`, rather than put all the code under `src/`.

**Comment by togimoto** [comment]
You are right. In any case, I think `Frontend/` should be changed to `frontend/`.

**Comment by yenting-biao** [comment]
y
