### ISSUE TITLE
[Backend] About `Pool`

### ISSUE THREAD

**Issue by yenting-biao** [112-1-Database-Management-Final-Project/ntu-book#51]
![image](https://github.com/112-1-Database-Management-Final-Project/ntu-book/assets/91837449/3fa43f57-3907-43d7-bc0d-712acd9c3f9d)

麻煩最後一個把 code 改完的人把 `index.js`的最後一行 `export const db = pool;` 拿掉，因為在其他檔案中還有 `import { db } from "../index.js";`，我如果先拿掉的話會大噴錯跑不動，故先暫時留在這裡（上面已經 `export pool` 了）。
Thanks!

**Comment by togimoto** [comment]
I will handle this.
