### ISSUE TITLE
post usedbook  and Comment bug

### ISSUE THREAD

**Issue by ZaiKuku** [112-1-Database-Management-Final-Project/ntu-book#58]
![image](https://github.com/112-1-Database-Management-Final-Project/ntu-book/assets/107979268/5c9cd869-d750-4847-9324-850df82f8c33)
有沒有可能是image的問題?我有試過傳base64進去但太大沒辦法傳
補充 postComment也不行

**Comment by togimoto** [comment]
Comment 測試是沒有問題，有沒有可能是你沒有用最新的復原檔？我原本也有 error 發現是 DB 沒有更新。
<img width="872" alt="image" src="https://github.com/112-1-Database-Management-Final-Project/ntu-book/assets/123284600/7cf4ff4d-dba7-4934-9e4f-a2e59f226965">

目前 Usedbook 是假設 BookPicture 是一個連結，如果 BookPicture 是一個連結則沒有問題：
![image](https://github.com/112-1-Database-Management-Final-Project/ntu-book/assets/123284600/26dec29b-125d-498c-a9bc-e6e1dd271e6b)

如果要傳 image 的 binary 的話應該要怎麼處理？我沒有處理 image 的經驗。

**Comment by ZaiKuku** [comment]
用url還是沒成功

**Comment by ZaiKuku** [comment]
我的錯 可以了
