### ISSUE TITLE
GetRequestsOfAUser Bug

### ISSUE THREAD

**Issue by ZaiKuku** [112-1-Database-Management-Final-Project/ntu-book#60]
不會回傳Requsets，沒有Error

**Comment by quevenliu** [comment]
是沒收到任何 response body 還是是空的data

API 文件是寫
empty "data" is returned if the user has not requested to buy this used book

**Comment by togimoto** [comment]
請問這是哪一個 api endpoint? (e.g., /api/usedbook/:id/comment)

如 queven 所說的，沒有 error 可能代表 body 是空的。

**Comment by ZaiKuku** [comment]
/api/usedbook/${id}/request
是收到空的data，但是我用資料庫裡有的request去查也拿不到資料
![image](https://github.com/112-1-Database-Management-Final-Project/ntu-book/assets/107979268/7bde28f0-671b-46b3-97b6-763f3e340a4a)
![image](https://github.com/112-1-Database-Management-Final-Project/ntu-book/assets/107979268/d5d564c6-39b6-4c71-bd47-eaa3f9e5173b)

**Comment by togimoto** [comment]
我這邊測試是沒有問題：
![image](https://github.com/112-1-Database-Management-Final-Project/ntu-book/assets/123284600/a3bce568-a5b2-4a1f-b481-9c66a5936d4b)

有沒有可能是目前登入的使用者帳號不是 b10704000 ?

**Comment by ZaiKuku** [comment]
抱歉我應該用另一支API!!
