### ISSUE TITLE
Get User Private Profile Bug

### ISSUE THREAD

**Issue by ZaiKuku** [112-1-Database-Management-Final-Project/ntu-book#61]
Ratings裡面的StudentID回傳null，其他資料回傳正常
然後我希望可以新增對應的usedBookid
![image](https://github.com/112-1-Database-Management-Final-Project/ntu-book/assets/107979268/b5018a2f-f2ad-44c2-84ba-0fcfc5e96868)

**Comment by quevenliu** [comment]
我目前 `UsedBooks` 是只有回傳還沒賣出的，所以可能找不到
想問一下你會想要
1. 直接回傳全部
2. 回傳+一個status

**Comment by togimoto** [comment]
他是指 ratings 的部分吧，就是 rating 的欄位裡面的 studentID 是 null，還有希望對每個 rating 附上對應的 usedbookid。

**Comment by quevenliu** [comment]
OK了解了 感謝
